baseURL = "/"
languageCode = "utf-8"
title = "TikTok Tracking Exposed"
theme = "trex"
enableRobotsTXT = true
canonifyURLs = true

[params]
#   ourvision = "not-display"
   subtitle = "TikTok Tracking Exposed"
   subsite = "tiktok"
   openGraphSiteName = "TikTok Tracking Exposed"
   description = "This is a collaborative project meant to let you take back control of your data. This approach do not follow corporate methods, but as an algorithm investigator let you passively records what Youtube algorithm pick for you, and let you play with the data."
   tagline = "This tool to study TikTok's personalization algorithm is now DISCONTINUED."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  posts = "/:slug/"

[menu]
 [[menu.main]]
    name = "About"
    url = "/about"
    weight = 2
 [[menu.main]]
    name = "Work"
    url = "/work"
    weight = 1
# [[menu.main]]
#    name = "MozFest"
#    url = "/slides/mozfest"
#    weight = 3
# [[menu.main]]
#    name = "Services"
#    url = "/services"
#    weight = 4

# [[menu.featured]]
#    name = "Build your own tktrex"
#    url = "/software"
#    pre = "/images/github.svg"
#    post = "Backend, parser, scraping extension, website — all AGPL-3 licensed"
#    weight = 1
# [[menu.featured]]
#    name= "Data Format and Tools"
#    url = "/docs/tktrex/api"
#    pre = "/images/csv.png"
#    post = "Which metadata can you extract from TikTok, and few tips on how you can use it as data analyst"
#    weight = 2
# [[menu.featured]]
#    name = "on Geo-Banning"
#    url = "/ws22-shadowban-research"
#    pre = "/images/imageglitcher-oflo.png"
#    weight = 3
#    post = "the DMI research sprint, in January'22 has explored geobanning via search keywords"

 [[menu.footer]]
    name = "We don't use cookies"
    url = "/cookies"
    weight = 100
 [[menu.footer]]
    name = "Privacy Statement"
    url = "/privacy"
    weight = 80
 [[menu.footer]]
    name = "Stats"
    url = "/stats"
    weight = 90
