baseURL = "/"
languageCode = "utf-8"
title = "TikTok Tracking Exposed"
theme = "trex"
enableRobotsTXT = true
canonifyURLs = true

[params]
   ourvision = "not-display"
   subtitle = "TikTok"
   subsite = "tiktok"
   openGraphSiteName = "TikTok Observatory"
   description = "This is a collaborative project meant to let you take back control of your data. This approach do not follow corporate methods, but as an algorithm investigator let you passively records what Youtube algorithm pick for you, and let you play with the data."
   tagline = "TikTok Observatory: investigating censorship and algorithmic demotion"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  posts = "/:slug/"

[menu]
 [[menu.main]]
    name = "About"
    url = "/about"
    weight = 1
 [[menu.main]]
    name = "Stats"
    url = "/stats"
    weight = 2
 #[[menu.main]]
 #   name = "Research"
 #   url = "/research"
 #   weight = 3
 #[[menu.main]]
 #   name = "Services"
 #   url = "/services"
 #   weight = 4

 [[menu.featured]]
    name = "Github repository"
    url = "https://github.com/tracking-exposed/tktrex"
    pre = "/images/github.svg"
    post = "Check our the source code, it is free softward"
    weight = 1
 [[menu.featured]]
    name= "Tracking Exposed, since 2016"
    url = "https://tracking.exposed"
    pre = "/images/trex-logo-180x180.jpg"
    post = "The umbrella project, check tools and researches on Facebook, YouTube, PornHub and Amazon"
    weight = 2
 [[menu.featured]]
    name = "DMI Winter School"
    url = "/winterschool22"
    pre = "images/digitalmethods.svg"
    weight = 3
    post = "TikTok TRex will be used during the Digital Methods Winter School at the Amsterdam University"

 [[menu.footer]]
    name = "Tracking Exposed"
    url = "https://tracking.exposed"
    weight = 90
 [[menu.footer]]
    name = "Privacy"
    url = "/privacy"
    weight = 80
