baseURL = "/"
languageCode = "utf-8"
title = "TikTok Tracking Exposed"
theme = "trex"
enableRobotsTXT = true
canonifyURLs = true

[params]
   ourvision = "not-display"
   subtitle = "TikTok"
   subsite = "tiktok"
   openGraphSiteName = "TikTok Observatory"
   description = "This is a collaborative project meant to let you take back control of your data. This approach do not follow corporate methods, but as an algorithm investigator let you passively records what Youtube algorithm pick for you, and let you play with the data."
   tagline = "TikTok Observatory: investigating censorship and algorithmic demotion"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  posts = "/:slug/"

[menu]
 [[menu.main]]
    name = "About"
    url = "/about"
    weight = 1
 [[menu.main]]
    name = "Stats"
    url = "/stats"
    weight = 2
 #[[menu.main]]
 #   name = "Research"
 #   url = "/research"
 #   weight = 3
 #[[menu.main]]
 #   name = "Services"
 #   url = "/services"
 #   weight = 4

 [[menu.featured]]
    name = "Git repository"
    url = "https://github.com/tracking-exposed/tktrex"
    pre = "/images/github.svg"
    post = "backend, parser, scraping extension, website — all AGPL-3 licensed"
    weight = 1
 [[menu.featured]]
    name= "Documentation"
    url = "/csv"
    pre = "/images/csv.png"
    post = "Which metadata can you extract from TikTok, and few tips on how you can use it as data analyst"
    weight = 2
 [[menu.featured]]
    name = "DMI Winter School"
    url = "/slides/ws22-pitch"
    pre = "/images/digitalmethods.svg"
    weight = 3
    post = "The research sprint that used this tool in development; part of Digital Methods Initiative at UvA"

 [[menu.footer]]
    name = "Tracking Exposed"
    url = "https://tracking.exposed"
    weight = 90
 [[menu.footer]]
    name = "Privacy"
    url = "/privacy"
    weight = 80
